# Generated by Django 5.1.5 on 2025-01-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('settlement', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('children', models.IntegerField()),
            ],
        ),
    ]
